address                = "0.0.0.0:8080"
workers                = 4
upload_path            = "./upload"
max_content_length     = 10_000_000 # 10MB
delete_expired_enabled = true # default: false
delete_expired_ttl     = "1d" # default: 86400s
